### ISSUE TITLE
Autocage give error

### ISSUE THREAD

**Issue by S4mmis** [Kruithne/AutoCage#17]
2x AutoCage/AutoCage.lua:142: table index is nil
[string "@AutoCage/AutoCage.lua"]:142: in function `AutoCage_HandleAutoCaging'
[string "@AutoCage/AutoCage.lua"]:291: in function `func'
[string "@AutoCage/AutoCage.lua"]:312: in function `?'
[string "@Blizzard_ChatFrameBase/Mainline/ChatFrame.lua"]:5468: in function `ChatEdit_ParseText'
[string "@Blizzard_ChatFrameBase/Mainline/ChatFrame.lua"]:5120: in function <Blizzard_ChatFrameBase/Mainline/ChatFrame.lua:5119>
[string "=[C]"]: in function `ChatEdit_SendText'
[string "@Blizzard_ChatFrameBase/Mainline/ChatFrame.lua"]:5156: in function <Blizzard_ChatFrameBase/Mainline/ChatFrame.lua:5152>
[string "=[C]"]: in function `ChatEdit_OnEnterPressed'
[string "*ChatFrame.xml:140_OnEnterPressed"]:1: in function <[string "*ChatFrame.xml:140_OnEnterPressed"]:1>

Locals:
petToCageID = nil
total = 0
owned = 1380
petCache = <table> {
}
(for index) = 1
(for limit) = 1380
(for step) = 1
index = 1
pGuid = nil
pBattlePetID = nil
_ = nil
pNickname = nil
pLevel = nil
pIsFav = nil
_ = nil
pName = nil
_ = nil
_ = nil
_ = nil
_ = nil
_ = nil
_ = nil
_ = nil
pIsTradeable = nil
(*temporary) = nil
(*temporary) = nil
(*temporary) = nil
(*temporary) = nil
(*temporary) = nil
(*temporary) = "table index is nil"
petsToCage = <table> {
}

**Comment by I-AM-T3X** [comment]
@S4mmis  was with this the fixes i added that @Kruithne  merged in the other day?

**Comment by I-AM-T3X** [comment]
also do you have any steps to recreate this @S4mmis

**Comment by S4mmis** [comment]
Everytime when i try /autocage cage

And addon not cage pet when i learn duplicate pets

**Comment by I-AM-T3X** [comment]
@S4mmis have you updated the addon with the fixes I implemented yesterday? the one on curseforge is broken. you need to download it directly from here. The version I have is working and its the same version that is on github

**Comment by S4mmis** [comment]
Yes downloaded it from here and now i redownloaded and installed it but same error keep poppin

**Comment by I-AM-T3X** [comment]
@S4mmis can you zip and attach your auto cage from both the addons folder and the WTF folder

**Comment by LiamGBR** [comment]
> @S4mmis have you updated the addon with the fixes I implemented yesterday? the one on curseforge is broken. you need to download it directly from here. The version I have is working and its the same version that is on github

found this after fixing addons is there a way to make WowUp client see updates on github?

**Comment by I-AM-T3X** [comment]
@LiamGBR  it would require @Kruithne to publish a release then wow up could pull it, if not they would need to give someone else the permissions to publish a release

**Comment by LiamGBR** [comment]
@I-AM-T3X ah ok thanks good to know for other addons trying to avoid enable notifications and then come manually download but not too important for this as probably only needs updating once every few years

**Comment by S4mmis** [comment]
[AutoCage.lua.zip](https://github.com/user-attachments/files/16645072/AutoCage.lua.zip)
[AutoCage.zip](https://github.com/user-attachments/files/16645073/AutoCage.zip)

**Comment by I-AM-T3X** [comment]
@S4mmis I’ve reviewed your files and don’t believe they would cause the code to fail. While there are some changes in the Italian translation, those shouldn't affect the code. The only thing I can suggest is that your Warcraft installation might be corrupt. It might be worth running a scan and repair. If that doesn't work, you might need to completely remove the addon from both your AddOns and WTF folders, restart the game, and then try reinstalling it. If the issue persists, please take notes and provide me with a step-by-step guide on how you’re triggering the bug, then I may be able to work backwards and figure out the issue.

**Comment by S4mmis** [comment]
> The only thing I can suggest is that your Warcraft installation might be corrupt. It might be worth running a scan and repair.

Done

> you might need to completely remove the addon from both your AddOns and WTF folders, restart the game, and then try reinstalling it.

Done

> step-by-step guide on how you’re triggering the bug, then I may be able to work backwards and figure out the issue.

Just typing **/autocage cage** give error
And none duplicate pet auto cage when i learn them. It doesn't matter if everything or not a single other addon is on

**Comment by I-AM-T3X** [comment]
@S4mmis  both your version and my version worked on my machine and did not trigger that error. so I do not know what is causing your error. Are you sure you have duplicate pets that can be caged?

**Comment by S4mmis** [comment]
> Are you sure you have duplicate pets that can be caged?

Yes!!!

**Comment by I-AM-T3X** [comment]
@S4mmis  then I don't know what's causing the issue
